### ISSUE TITLE
Conversion always fails

### ISSUE THREAD

**Issue by kran27** [terry-haire/fnv-to-fo4#6]
![image](https://github.com/terry-haire/fnv-to-fo4/assets/56488228/e976ea94-8d13-41a6-b0a2-eed4440d0078)
I've set everything up as it says to, every version i've tried fails like this after extracting textures.

**Comment by terry-haire** [comment]
Thank you for reporting the issue. Unfortunately I was not able to reproduce the issue. In the latest version this creates a warning instead of a crash. However, the next step might crash. Please reopen the ticket if this is the case.
